### ISSUE TITLE
About Synthesis Rain

### ISSUE THREAD

**Issue by ShenZheng2000** [kuijiang0802/MSPFN#24]
Hello, authors! I would like to know how you synthesis the rain for task-driven datasets. In the paper, you mention that you "create three new synthesis rain datasets ... through Photoshop". Could you provide a link for how you made those rain streaks? Thanks in advance.

**Comment by kuijiang0802** [comment]
There are several ways to add the rain streaks, such that
http://www.coozhi.com/youxishuma/diannao/4511.html
https://www.jb51.net/photoshop/117900.html

**Comment by ShenZheng2000** [comment]
> There are several ways to add the rain streaks, such that
> http://www.coozhi.com/youxishuma/diannao/4511.html
> https://www.jb51.net/photoshop/117900.html

**Comment by ShenZheng2000** [comment]
> > There are several ways to add the rain streaks, such that
> > http://www.coozhi.com/youxishuma/diannao/4511.html
> > https://www.jb51.net/photoshop/117900.html

Thanks.
